# Generated by Django 5.2.4 on 2025-07-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('Nationality', models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('FR', 'France'), ('JP', 'Japan'), ('IN', 'India'), ('BR', 'Brazil'), ('CN', 'China'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('KR', 'Korea')], default='US', max_length=50)),
            ],
        ),
    ]
